"use client"

import { useState } from "react"
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx"
import { saveAs } from "file-saver"
import { Button } from "@/components/ui/button"
import { Download, Loader2 } from "lucide-react"

interface IEPData {
  student?: {
    name?: string
    dob?: string
    grade?: string
    school?: string
    district?: string
  }
  eligibility?: {
    primary_disability?: string
    secondary_disability?: string
  }
  plaafp?: {
    academic?: string
    functional?: string
    strengths?: string
    concerns?: string
  }
  goals?: Array<{
    area?: string
    goal?: string
    baseline?: string
    target?: string
    objectives?: string[]
    clinical_notes?: string
  }>
  services?: Array<{
    service?: string
    frequency?: string
    duration?: string
    location?: string
    provider?: string
  }>
  accommodations?: string[]
  lre?: {
    placement?: string
    justification?: string
    time_general_ed?: string
  }
}

interface DownloadIEPButtonProps {
  iepData: IEPData
  complianceScore?: number
  state?: string
  stateName?: string
  variant?: "default" | "outline" | "ghost"
  className?: string
}

export function DownloadIEPButton({
  iepData,
  complianceScore,
  state,
  stateName,
  variant = "default",
  className = "",
}: DownloadIEPButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false)

  const generateDocument = async () => {
    setIsGenerating(true)

    try {
      const studentName = iepData.student?.name || "Student"
      const today = new Date().toLocaleDateString()

      // Create document sections
      const children: Paragraph[] = []

      // Title
      children.push(
        new Paragraph({
          text: "INDIVIDUALIZED EDUCATION PROGRAM (IEP)",
          heading: HeadingLevel.TITLE,
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
      )

      // Compliance badge
      if (complianceScore !== undefined) {
        children.push(
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
            children: [
              new TextRun({
                text: `${complianceScore}% ${stateName || state || ""} Compliant`,
                bold: true,
                color: complianceScore >= 80 ? "22863A" : complianceScore >= 60 ? "B45309" : "DC2626",
              }),
            ],
          }),
        )
        children.push(
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
            children: [
              new TextRun({
                text: `Generated by EASI IEP on ${today}`,
                italics: true,
                size: 20,
                color: "666666",
              }),
            ],
          }),
        )
      }

      // Student Information Section
      children.push(
        new Paragraph({
          text: "STUDENT INFORMATION",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        }),
      )

      const studentInfo = [
        { label: "Student Name", value: iepData.student?.name },
        { label: "Date of Birth", value: iepData.student?.dob },
        { label: "Grade", value: iepData.student?.grade },
        { label: "School", value: iepData.student?.school },
        { label: "District", value: iepData.student?.district },
        { label: "Primary Disability", value: iepData.eligibility?.primary_disability },
        { label: "Secondary Disability", value: iepData.eligibility?.secondary_disability },
      ]

      studentInfo.forEach(({ label, value }) => {
        if (value && value !== "Unknown") {
          children.push(
            new Paragraph({
              spacing: { after: 100 },
              children: [new TextRun({ text: `${label}: `, bold: true }), new TextRun({ text: value })],
            }),
          )
        }
      })

      // PLAAFP Section
      children.push(
        new Paragraph({
          text: "PRESENT LEVELS OF ACADEMIC ACHIEVEMENT AND FUNCTIONAL PERFORMANCE (PLAAFP)",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        }),
      )

      if (iepData.plaafp?.strengths) {
        children.push(
          new Paragraph({
            spacing: { after: 100 },
            children: [
              new TextRun({ text: "Strengths: ", bold: true }),
              new TextRun({ text: iepData.plaafp.strengths }),
            ],
          }),
        )
      }

      if (iepData.plaafp?.concerns) {
        children.push(
          new Paragraph({
            spacing: { after: 100 },
            children: [
              new TextRun({ text: "Areas of Concern: ", bold: true }),
              new TextRun({ text: iepData.plaafp.concerns }),
            ],
          }),
        )
      }

      if (iepData.plaafp?.academic) {
        children.push(
          new Paragraph({
            spacing: { after: 100 },
            children: [
              new TextRun({ text: "Academic Performance: ", bold: true }),
              new TextRun({ text: iepData.plaafp.academic }),
            ],
          }),
        )
      }

      if (iepData.plaafp?.functional) {
        children.push(
          new Paragraph({
            spacing: { after: 100 },
            children: [
              new TextRun({ text: "Functional Performance: ", bold: true }),
              new TextRun({ text: iepData.plaafp.functional }),
            ],
          }),
        )
      }

      // Goals Section
      if (iepData.goals && iepData.goals.length > 0) {
        children.push(
          new Paragraph({
            text: "ANNUAL GOALS",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
        )

        iepData.goals.forEach((goal, index) => {
          children.push(
            new Paragraph({
              text: `Goal ${index + 1}: ${goal.area || "General"}`,
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 200, after: 100 },
            }),
          )

          if (goal.goal) {
            children.push(
              new Paragraph({
                spacing: { after: 100 },
                children: [new TextRun({ text: "Goal: ", bold: true }), new TextRun({ text: goal.goal })],
              }),
            )
          }

          if (goal.baseline) {
            children.push(
              new Paragraph({
                spacing: { after: 100 },
                children: [new TextRun({ text: "Baseline: ", bold: true }), new TextRun({ text: goal.baseline })],
              }),
            )
          }

          if (goal.target) {
            children.push(
              new Paragraph({
                spacing: { after: 100 },
                children: [new TextRun({ text: "Target: ", bold: true }), new TextRun({ text: goal.target })],
              }),
            )
          }

          if (goal.objectives && goal.objectives.length > 0) {
            children.push(
              new Paragraph({
                spacing: { before: 100 },
                children: [new TextRun({ text: "Objectives:", bold: true })],
              }),
            )
            goal.objectives.forEach((obj, objIndex) => {
              children.push(
                new Paragraph({
                  spacing: { after: 50 },
                  indent: { left: 720 },
                  children: [new TextRun({ text: `${objIndex + 1}. ${obj}` })],
                }),
              )
            })
          }
        })
      }

      // Services Section
      if (iepData.services && iepData.services.length > 0) {
        children.push(
          new Paragraph({
            text: "SPECIAL EDUCATION AND RELATED SERVICES",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
        )

        iepData.services.forEach((service, index) => {
          children.push(
            new Paragraph({
              text: `Service ${index + 1}: ${service.service || "Service"}`,
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 200, after: 100 },
            }),
          )

          const serviceDetails = [
            { label: "Frequency", value: service.frequency },
            { label: "Duration", value: service.duration },
            { label: "Location", value: service.location },
            { label: "Provider", value: service.provider },
          ]

          serviceDetails.forEach(({ label, value }) => {
            if (value) {
              children.push(
                new Paragraph({
                  spacing: { after: 50 },
                  children: [new TextRun({ text: `${label}: `, bold: true }), new TextRun({ text: value })],
                }),
              )
            }
          })
        })
      }

      // Accommodations Section
      if (iepData.accommodations && iepData.accommodations.length > 0) {
        children.push(
          new Paragraph({
            text: "ACCOMMODATIONS AND MODIFICATIONS",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
        )

        iepData.accommodations.forEach((accommodation, index) => {
          children.push(
            new Paragraph({
              spacing: { after: 50 },
              bullet: { level: 0 },
              children: [new TextRun({ text: accommodation })],
            }),
          )
        })
      }

      // LRE Section
      if (iepData.lre) {
        children.push(
          new Paragraph({
            text: "LEAST RESTRICTIVE ENVIRONMENT (LRE)",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
        )

        if (iepData.lre.placement) {
          children.push(
            new Paragraph({
              spacing: { after: 100 },
              children: [
                new TextRun({ text: "Placement: ", bold: true }),
                new TextRun({ text: iepData.lre.placement }),
              ],
            }),
          )
        }

        if (iepData.lre.time_general_ed) {
          children.push(
            new Paragraph({
              spacing: { after: 100 },
              children: [
                new TextRun({ text: "Time in General Education: ", bold: true }),
                new TextRun({ text: iepData.lre.time_general_ed }),
              ],
            }),
          )
        }

        if (iepData.lre.justification) {
          children.push(
            new Paragraph({
              spacing: { after: 100 },
              children: [
                new TextRun({ text: "Justification: ", bold: true }),
                new TextRun({ text: iepData.lre.justification }),
              ],
            }),
          )
        }
      }

      // Footer
      children.push(
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 800 },
          children: [
            new TextRun({
              text: "This IEP was generated using EASI IEP and validated for compliance with ",
              size: 18,
              color: "666666",
            }),
            new TextRun({
              text: `${stateName || state || "federal"} regulations and IDEA requirements.`,
              size: 18,
              color: "666666",
            }),
          ],
        }),
      )

      // Create document
      const doc = new Document({
        sections: [
          {
            properties: {},
            children,
          },
        ],
      })

      // Generate and download
      const blob = await Packer.toBlob(doc)
      const fileName = `IEP_${studentName.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.docx`
      saveAs(blob, fileName)
    } catch (error) {
      console.error("[v0] Error generating document:", error)
      alert("Failed to generate document. Please try again.")
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <Button onClick={generateDocument} disabled={isGenerating} variant={variant} className={className}>
      {isGenerating ? (
        <>
          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          Generating...
        </>
      ) : (
        <>
          <Download className="mr-2 h-4 w-4" />
          Download Final IEP
        </>
      )}
    </Button>
  )
}
